Search API
JSD-0423/backend-final-3 pull request #7
Opened 2023-07-12 23:26 UTC by qusai122

2023-07-12 23:27 UTC, qusai122 commented
the first 3 commits are form the previous Branch

2023-07-13 07:53 UTC, mshareef-kiitos requested changes

2023-07-13 07:53 UTC, mshareef-kiitos commented on src/app.ts
> +import ProductRouts from '@routes/product';
Correct the spelling to be: `ProductRoutes`

2023-07-13 07:53 UTC, mshareef-kiitos commented on src/controllers/product.ts
> +export const Popular: RequestHandler = async (req, res) => {
Use small-first character and make it more descriptive name like: `getPopular`

2023-07-13 07:53 UTC, mshareef-kiitos commented on src/controllers/product.ts
> +export const newArrivals: RequestHandler = async (req, res) => {
Make it more descriptive name like: `getNewArrivals`

2023-07-13 07:53 UTC, mshareef-kiitos commented on src/controllers/product.ts
> +export const Handpicked: RequestHandler = async (req, res) => {
Same, rename it to `getHandpicked`

2023-07-13 07:53 UTC, mshareef-kiitos commented on src/controllers/product.ts
> +  const { maxPrice } = query;
Desctructure all of the above using one line:
`const { limited, discount, rating, isNew, handpicked, minPrice, maxPrice } = query;`

2023-07-13 07:53 UTC, mshareef-kiitos commented on src/controllers/product.ts
> +  const filter = createFilter(req.query);
If it will be a static filter like `{ handpicked: '1' }`. Then call it like `createFilter({ handpicked: '1' })`

2023-07-13 07:53 UTC, mshareef-kiitos commented on src/controllers/product.ts
> +async function getProductsByFilter(filter) {
This function should be moved to services directory. All the functions in the controller should be to handle requests only

2023-07-13 07:53 UTC, mshareef-kiitos commented on src/controllers/product.ts
> +function createFilter(query: ParsedQs) {
This function should be moved to services directory. All the functions in the controller should be to handle requests only

2023-07-13 07:53 UTC, mshareef-kiitos commented on src/controllers/product.ts
> +    threeMonthsAgo.setMonth(currentDate.getMonth() - 3);
Add a function in the utils that retrieves the date of new arrivals, so you can use it everywhere instead of settings the months everywhere you need it (one point of change). Suggested name for the function: `getNewArrivalsEarliestDate`

2023-07-13 07:53 UTC, mshareef-kiitos commented on src/routes/product.ts
> +} from '@controllers/product';
Great usage for the `@controllers`!

2023-07-13 07:53 UTC, mshareef-kiitos commented on src/controllers/product.ts
> +  console.log(filter);
Remove the console.

2023-07-13 07:53 UTC, mshareef-kiitos commented on src/controllers/product.ts
> +  let filter = {};
You can use `const`, since you are changing the properties of the filter, not reassign it.

2023-07-13 07:53 UTC, mshareef-kiitos commented on src/controllers/product.ts
> +  try {
For this and the other functions, add the `try` brackets all over the code, even if you're assigning. It's a better practice for using try-catch.

2023-07-13 12:10 UTC, closed without merging